SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "TyrianNavi"

PLAYER_SPEED = 5
BULLET_SPEED = 7
ENEMY_SPEED = 2
BULLET_OFFSET = 20
SPAWN_RATE = 1.0  # Cada segundo aparece un enemigo}

PLAYER_LIVES=15
SCORE=0